spring.application.name=SpringBootPropertiesDemo
#paymentGateway.type=paytm
#paymentGateway.retrycount=5

payment-properties.type=Razorpay
payment-properties.retry-count=5
payment-properties.isEnabled=true
payment-properties.timeout=3000
